workflows:
  ios-custom-build:
    name: Build Telegram iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/telegram-bazel-cache

    scripts:
      - name: Fetch submodules
        script: |
          git submodule update --init --recursive

      - name: Prepare build environment
        script: |
          mkdir -p build-input
          mkdir -p $HOME/telegram-bazel-cache
          
          # Отключение лишних расширений
          echo "build --//Telegram:disableExtensions" >> .bazelrc
          
          # Скачиваем недостающий компонент Xcode для компиляции графики Metal
          xcodebuild -downloadComponent MetalToolchain
          
          # Создаем фейковый скрипт подписи, который возвращает пустой JSON
          echo '#!/bin/bash' > fake_codesign.sh
          echo 'echo "{}"' >> fake_codesign.sh
          chmod +x fake_codesign.sh

      - name: Generate Local Provisioning & Build App
        script: |
          # 1. Генерация проекта (подсовываем пустой JSON подписи)
          python3 build-system/Make/Make.py \
            --overrideXcodeVersion \
            --overrideBazelVersion \
            generateProject \
            --configurationPath build-system/appstore-configuration.json \
            --codesigningInformationPath $PWD/fake_codesign.sh \
            --disableProvisioningProfiles \
            --disableExtensions

          # 2. Сборка (теперь Bazel соберет Ad-Hoc IPA без официальных сертификатов)
          python3 build-system/Make/Make.py \
            --overrideXcodeVersion \
            --overrideBazelVersion \
            --cacheDir="$HOME/telegram-bazel-cache" \
            build \
            --buildNumber 1 \
            --configuration release_arm64 \
            --configurationPath build-system/appstore-configuration.json \
            --codesigningInformationPath $PWD/fake_codesign.sh

    artifacts:
      - bazel-bin/Telegram/Telegram.ipa
      - bazel-bin/Telegram/Telegram.app
