workflows:
  ios-custom-build:
    name: Build Telegram iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/telegram-bazel-cache

    scripts:
      - name: Fetch submodules
        script: |
          git submodule update --init --recursive

      - name: Prepare build environment
        script: |
          mkdir -p build-input
          mkdir -p $HOME/telegram-bazel-cache

      - name: Generate Local Provisioning & Build App
        script: |
          # 1. Генерация проекта (отключаем расширения)
          python3 build-system/Make/Make.py \
            --overrideXcodeVersion \
            --overrideBazelVersion \
            generateProject \
            --configurationPath build-system/appstore-configuration.json \
            --xcodeManagedCodesigning \
            --disableProvisioningProfiles \
            --disableExtensions

          # 2. Сборка (добавлен знак "=" для корректной передачи аргументов)
          python3 build-system/Make/Make.py \
            --overrideXcodeVersion \
            --overrideBazelVersion \
            --cacheDir="$HOME/telegram-bazel-cache" \
            --bazelArguments="--//Telegram:disableExtensions" \
            build \
            --buildNumber 1 \
            --configuration release_arm64 \
            --configurationPath build-system/appstore-configuration.json \
            --xcodeManagedCodesigning

    artifacts:
      - bazel-bin/Telegram/Telegram.ipa
      - bazel-bin/Telegram/Telegram.app
